INSERT INTO products (name, description, price, brand, category, image_url) VALUES
('iPhone 15', 'Latest Apple smartphone with A16 Bionic chip', 999.99, 'Apple', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/iphone15.jpg'),
('Samsung Galaxy S23', 'Android flagship with 200MP camera', 899.99, 'Samsung', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/galaxys23.jpg'),
('Levi''s 501 Jeans', 'Classic straight fit jeans', 89.95, 'Levi''s', 'FASHION', 'https://res.cloudinary.com/demo/image/upload/levis501.jpg'),
('Kindle Paperwhite', 'Waterproof e-reader with 6.8" display', 139.99, 'Amazon', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/kindle_pw.jpg'),
('Nike Air Max 270', 'Comfortable lifestyle shoes', 150.00, 'Nike', 'FASHION', 'https://res.cloudinary.com/demo/image/upload/airmax270.jpg'),
('The Great Gatsby', 'Classic novel by F. Scott Fitzgerald', 12.99, 'Scribner', 'BOOKS', 'https://res.cloudinary.com/demo/image/upload/gatsby.jpg'),
('Bose QuietComfort 45', 'Noise-cancelling headphones', 329.00, 'Bose', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/bose_qc45.jpg'),
('Adidas Ultraboost 22', 'Responsive running shoes', 190.00, 'Adidas', 'FASHION', 'https://res.cloudinary.com/demo/image/upload/ultraboost22.jpg'),
('Dyson V15 Detect', 'Cordless vacuum cleaner', 699.99, 'Dyson', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/dyson_v15.jpg'),
('Harry Potter Box Set', 'Complete 7-book collection', 98.50, 'Bloomsbury', 'BOOKS', 'https://res.cloudinary.com/demo/image/upload/hp_boxset.jpg'),
('MacBook Pro 16"', 'M2 Max chip, 32GB RAM', 2499.00, 'Apple', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/mbp16.jpg'),
('Sony WH-1000XM5', 'Premium noise-cancelling headphones', 399.99, 'Sony', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/sony_xm5.jpg'),
('Calvin Klein T-Shirt', 'Cotton crew neck tee', 29.99, 'Calvin Klein', 'FASHION', 'https://res.cloudinary.com/demo/image/upload/ck_tee.jpg'),
('Instant Pot Duo', '7-in-1 electric pressure cooker', 99.95, 'Instant Pot', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/instant_pot.jpg'),
('Atomic Habits', 'Self-help book by James Clear', 14.99, 'Avery', 'BOOKS', 'https://res.cloudinary.com/demo/image/upload/atomic_habits.jpg'),
('GoPro Hero 11', '5.3K action camera', 399.99, 'GoPro', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/gopro11.jpg'),
('Zara Trench Coat', 'Classic beige trench coat', 199.90, 'Zara', 'FASHION', 'https://res.cloudinary.com/demo/image/upload/zara_trench.jpg'),
('The Alchemist', 'Novel by Paulo Coelho', 10.99, 'HarperOne', 'BOOKS', 'https://res.cloudinary.com/demo/image/upload/alchemist.jpg'),
('Fitbit Charge 5', 'Advanced fitness tracker', 149.95, 'Fitbit', 'ELECTRONICS', 'https://res.cloudinary.com/demo/image/upload/fitbit5.jpg'),
('Ray-Ban Aviator', 'Classic sunglasses', 153.00, 'Ray-Ban', 'FASHION', 'https://res.cloudinary.com/demo/image/upload/rayban_aviator.jpg');